[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cp_amm = "qRBW9ZquC4NXj1Q8zFqMxvJoNwvFfwD2Mznf8G8rrns"
lending_pool = "E65Dsa4sKTEG5XPQSWzshvRBboCSLUrGZZyovuGMPQfn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "keys/local/admin-bossj3JvwiNK7pvjr149DqdtJxf2gdygbcmEPTkb2F1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/lendingPool.test.ts"
